### ISSUE TITLE
Wrong result (at most %d times)

### ISSUE THREAD

**Issue by semyon-san** [javallone/regexper-static#14]
If you enter this:
(?:[\d]{1,3})\.(?:[\d]{1,3})\.(?:[\d]{1,3})\.(?:[\d]{1,3})

It's going to say:
 One of: digit at most 2 times
When it should say at most 3 times.

**Comment by ThibWeb** [comment]
Hey @semyon-san, I stumbled upon this too. You can reproduce this with a very simple regex, like:

```
# Just a
a{1}
# a, loop once
a{2}
```

I think what it means is "One of those digits, and then loop at most 2 times" (which is 3 in total). This is admittedly very confusing. I'd like to propose a PR to change this behavior.

**Comment by javallone** [comment]
@ThibWeb you are correct in your interpretation. I'm specifically indicating the loop count as one less than what the expression requests since the label is associated with the portion of the path that loops back. So, if you're following the path through the diagram, you go through the portion to be repeated once, then follow the loop path as indicated in the label.

The original version of Regexper actually reported it as requested by this issue (`x{2}` would say "2 times"), but there were issues brought up with that indicating that the count was off per the diagram. During the redesign, I went back and forth with this choice a lot, and I'm not happy with either option (and haven't come up with any better ideas). Using the exact number is inaccurate for the diagram, and the current setup requires a call out in the documentation and leads to issues being opened occasionally.

I'd love to find a better way to indicate the repetition count that is accurate for the diagram and doesn't lead to confusion like this.

**Comment by ThibWeb** [comment]
That's a tough one. The diagram definitely is more accurate with the label on the loop being - 1 the repetition instead of just the repetition.

I've had a look around the internet for ways to visually represent loops and iteration count in diagrams / programming language visualizations. The closest thing I could find were block-based visual programming languages, https://developers.google.com/blockly/ and https://scratch.mit.edu/. I couldn't find any decisive info.

As a programmer I tend to think of `x{N}` as "x being looped over N times", as in a `for` loop. IMHO the diagram would be much clearer to me if it represented:

- The fact that there's a loop going on, with the arrow.
- The repetition count, with a number.

In terms of rendering, it could look like that:

<img width="359" alt="regexper-loop-label-test" src="https://cloud.githubusercontent.com/assets/877585/9647522/fdad7952-5231-11e5-8c06-669ae94b950f.png">
[`[\d]{1,999}`](http://regexper.com/#%5B%5Cd%5D%7B1%2C999%7D)

- The loop count is a label for the thing that is being looped on.
- The loop path still conveys that there is some looping going on.

With the top label, it reads quite well from top to bottom ("One of: digits 1...999 times"). However, this is a very simple example and it might not work as well for bigger ones (like [`([\w]{3}|[\d]{10}){5}`](http://regexper.com/#(%5B%5Cw%5D%7B3%7D%7C%5B%5Cd%5D%7B10%7D)%7B5%7D)). It also has the drawbacks of making the charts a little bit bigger (to fit the label inside the loop path), and being a change from what people are used to (albeit for the better).

What do you think?

**Comment by javallone** [comment]
I think you're right, something like this will probably be the best option. 

The only situation I've been able to come up with where it doesn't quite work is a wide expression like [(?:foo[a-z][^abc]\r){1,5}](http://regexper.com/#(%3F%3Afoo%5Ba-z%5D%5B%5Eabc%5D%5Cr)%7B1%2C5%7D). In that case, the label would get lost or would appear to label a single part of the expression instead of the whole.

I do really like the idea of labeling the repeated content. That does seem to get around the issues nicely.

**Comment by hexinteractive** [comment]
I agree with ThibWeb's solution. And as for making the diagrams bigger, well I use regexper for clarity not compactness.

**Comment by ThibWeb** [comment]
@hexinteractive thanks for the feedback!

@javallone yep, that's a tricky case. As far as I understand (my regex knowledge only goes so far), that's a non-capturing group, and since it is non-capturing it is not rendered on the diagram.

For groups it works quite well with the repetition label under the group. For non-capturing groups... would it make sense to render them on the diagram nonetheless? It is more of a way to bypass the issue rather than a proper fix, but that'd work quite well.

I'm assuming that non-capturing groups are parsed by regexper just as regular groups are. Not sure how relevant it'd be to have them displayed on the diagram, even if they got a label like "non-capturing group #1". We can also come up with something else if this doesn't make sense.

**Comment by ph-One** [comment]
I've never actually found this to be an issue. It reads and flows exactly as expected. Looping is not an option until _after_ you first match the pattern, so the loop showing `n-1` makes sense to me.
:beers:

**Comment by ThibWeb** [comment]
While working on another project I've had an idea for another potential solution to this problem. It does not change the rendering of the diagrams, but adds an unobtrusive tooltip - the standard HTML tooltip displayed by the `title` attribute in HTML, and `<title>` tag in SVG. The text of that tooltip doesn't have to be as concise as the label on the diagram, and can thus explain exactly what the label means.

Here is my naive implementation:

![tooltip-demo](https://cloud.githubusercontent.com/assets/877585/17156370/2a5e47ee-5392-11e6-9279-d0009b0ff3a8.gif)

Notice that the presence of the tooltip is only conveyed by the mouse cursor set to `help` – which is a clue, but quite an obscure one. It's not the best solution, but it is fairly simple to implement and I don't think it comes with drawbacks. The obvious one is browser support (touch screens) - I need to try this out to see how bad it is.

@javallone what do you think?  I did a [quick implementation](https://github.com/ThibWeb/regexper-static/commit/ba160c2ad83c280798e0de6e8c271e36372bb17e) to demonstrate this but I would be keen to make a more proper PR if the solution is of interest.

If someone wants to try this out I have pushed a compiled version of my fork at: https://rawgit.com/ThibWeb/regexper-static/demo-repeat-tooltip/#(%5B%5Cw%5D%7B3%7D%7C%5B%5Cd%5D%7B10%7D)%7B5%7D

**Comment by javallone** [comment]
@ThibWeb I love this idea, and a PR would be greatly appreciated! From looking at your demo implementation, my only requests would be that the `cursor: help` style go in src/sass/svg.scss and that the logic to figure out the tooltip's label go in src/js/parser/javascript/repeat.js (I'm guessing that all of this was just done in one file to make the demo easier). 

Thanks for keeping this issue in mind. I had honestly run out of ideas for good solutions to it.
