### ISSUE TITLE
JS Uncaught TypeError

### ISSUE THREAD

**Issue by paulkeogh** [javallone/regexper-static#21]
Built from github. 

I see the following error in the browser console;

Uncaught TypeError: (0 , u.default) is not a function (typeof.js:11)

and there is no diagram displayed.

**Comment by javallone** [comment]
What browser are you running?

**Comment by paulkeogh** [comment]
Hi,

I am running Google Chrome 47.0.2526.106 (64 bit) on CentOS 6.5

Let me know if you want any more testing done.

Thanks,

**Comment by paulkeogh** [comment]
Same result on Firefox - Mozilla/5.0 (X11; Linux x86_64; rv:38.0)
Gecko/20100101 Firefox/38.0

**Comment by javallone** [comment]
Thank you, I am seeing the same problem. It looks like it only happens when running the site locally (regexper.com isn't exhibiting the error). It may be due to some bad interaction between NPM deps that have seen updates since the last deployment. I'll be pushing a change to update versions shortly.
