### ISSUE TITLE
Limiting Repetition Syntax Evaluation Displays the Wrong Length

### ISSUE THREAD

**Issue by jdgiotta** [javallone/regexper-static#6]
When render the model for the following pattern it gives the wrong character repetition size
\(?(\d{4})\)?\s?([2-9]\d{3})-?(\d{5})

Observed:
![tt-phonenumber](https://cloud.githubusercontent.com/assets/1541999/6602438/1e32c332-c7f2-11e4-93af-d3d5ce0a4da2.jpg)

Expected:
![regexper-bug](https://cloud.githubusercontent.com/assets/1541999/6602479/4c4271be-c7f2-11e4-948b-c1938ffb63cc.JPG)

**Comment by jdgiotta** [comment]
``/\(?(\d{4})\)?\s?([2-9]\d{3})-?(\d{5})/``

Sorry looks like GitHub escaped some characters.

**Comment by javallone** [comment]
Thank you for the feedback, but this is actually intentional. 

I went back and forth on this while working on regexper, and the original version actually worked as you're describing. In the end, I decided that the label should indicate the number of times the path is followed because of the label's proximity to the loop path. As a result, something like `(foo){5}` is going to be labeled "4 times" since the flow will have already gone through "foo" once already, leaving four more trips through to satisfy the expression.
