### ISSUE TITLE
Repetition counts are off by one

### ISSUE THREAD

**Issue by ericbock** [javallone/regexper-static#9]
`.{3}` results in 
![regexper](https://cloud.githubusercontent.com/assets/188078/7707535/4673c2b2-fe1e-11e4-9962-82293b7ce779.png)

**Comment by javallone** [comment]
This is actually a deliberate design decision. The label indicates the number of times that branch of the diagram is followed, and since you would have to go through the "any character" portion to get there the label is one less to account for that. It's covered in the [documentation](http://regexper.com/documentation.html) in the Quantifiers - Range section at the end of the page.

This is actually a decision that I went back and forth on for a while during the rewrite a few months ago. Both styles have their good and bad sides, and both can be argued to be "incorrect" in some way. The [original regexper](http://github.com/javallone/regexper) behaved as you describe (the label would have been "3 times"), but I thought the current behavior was more accurate when reading the diagram.
